### ISSUE TITLE
yaml data format?

### ISSUE THREAD

**Issue by dplepage** [endless-sky/endless-sky#551]
The data format is concise and very fast to parse, but as far as I can tell it's entirely a custom format. It'd be cool if the data files used something more standard like yaml (or json, or even XML). This would make it much easier to write non-C++ editors for the map, ships, etc.

I'd love to see a map & mission editor written in javascript, for example, the end result being a set of static pages that would let you edit your local files directly in your browser (conceivably someone could even host an online version of it?).

**Comment by Pointedstick** [comment]
Oh god, not XML. Heaven protect us from the horrorshow of human-written XML!

**Comment by bobafetthotmail** [comment]
Why you want to add the total bs sintax of json or xml on perfectly readable data files? U mad bro?

>"I'd love to see a map & mission editor written in javascript, for example,"

If the main game can parse the data files and is opensource, why another program cannot parse the same data files? Can't you clone the relevant code and fix a bit the syntax? Both C++ and javascript are object-oriented, it shouldn't be horribly difficult.
And even then, there are C++ to javascript converters like this http://kripken.github.io/emscripten-site/

It's probably easier to just modify the main game to have a map/mission editor since it can already read the data files.

Anyway, there is a beta map editor here https://github.com/endless-sky/endless-sky-editor/releases
and a ship building aid here https://github.com/endless-sky/endless-sky/wiki/CreatingShips

**Comment by endless-sky** [comment]
Having worked both as a TA and as a software engineer who has to interact with programmers of all different skill levels, I've found that one of the hardest things for non-programmers and novices is matching up their opening and closing brackets. The problem is that source code communicates its structure to a human via indentation, and to the computer via brackets. So, you continuously have problems where someone thinks the program says one thing, but the computer thinks it says something else.

That's where I think Python's idea of using whitespace to communicate program structure is great for beginning programmers, and that's why I chose a custom data format that uses that same idea. It makes it a little harder to parse, but not by much - you could probably write a parser in 20-30 lines of javascript.

As for XML, in my day job we had one team that decided to write all their configuration files in XML, whereas I decided mine would be plain text key-value pairs. Guess which one turned into a maintenance nightmare...

**Comment by dplepage** [comment]
Yes, this is why I'm mainly suggesting YAML, which uses whitespace for structure similar to how Python does things. If we used JSON or XML they'd only be editable via software, which would be a pain.

In YAML, the data would look very similar to how it does currently:
```yaml
Acamar:
  pos: [-284, -3]
  government: Syndicate
  habitable: 1080
  links:
    - Diphda
    - Aldebaran
    - Elnath
    - Kugel
  asteroids:
    - ["medium rock", 2, 2.352]
    - ["large rock", 1, 1.4952]
    - ["small metal", 3, 1.9488]
    - ["medium metal", 19, 2.2848]
    - ["large metal", 12, 2.352]
  trade:
    Clothing: 297
    Electronics: 620
    Equipment: 581
    Food: 390
    Heavy Metals: 875
    Industrial: 694
    Luxury Goods: 1395
    Medical: 576
    Metal: 249
    Plastic: 483
  fleets:
    - ["Large Core Merchants", 3000]
    - ["Small Core Merchants", 2000]
    - ["Small Republic", 3600]
    - ["Small Syndicate", 3200]
  objects:
    - sprite: star/g0
      period: 10
    - sprite: planet/lava2
      distance: 174.69
      period: 28.1028
    - sprite: planet/ice0
      distance: 396.53
      period: 96.1086
    - sprite: planet/rock9
      distance: 798.37
      period: 274.571
      objects:
        - sprite: planet/dust7
          distance: 149
          period: 20.7539
    - sprite: planet/cloud1
      distance: 1350.62
      period: 604.154
    - sprite: planet/dust3
      distance: 4090.18
      period: 3183.92
```

And yeah, it wouldn't be hard to write a parser in another language for the existing `DataNode` format, but why make people do that when YAML parsers already exist in almost all languages?

Also of note: Github supports syntax-highlighting for YAML, and my editor has various YAML-specific features; it's unlikely that anyone would take the time to make specific editor plugins for the existing custom format.
